image:
  repository: ghcr.io/krystal/zadara-exporter
  tag: null
  pullPolicy: IfNotPresent
  imagePullSecrets: null

service:
  type: ClusterIP
  port: 9090

configSecretName: null
configSecretKey: null

config:
  targets:
    []
    # - name: ""
    #   url: ""
    #   token: ""
    #   cloud_name: ""

metrics:
  serviceMonitor:
    enabled: false
    interval: 30s

deployment:
  argocd: false

nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
affinity: {}
tolerations: {}
