image:
  repository: ghcr.io/krystal/zadara-exporter
  tag: null
  pullPolicy: IfNotPresent
  imagePullSecrets: null

service:
  type: ClusterIP
  port: 9090


configSecretName: ""
configSecretKey: ""

config:
  listen_address: :9090
  listen_path: /metrics
  targets:
    - name: ''
      url: ''
      token: ''
      cloud_name: ''

metrics:
  serviceMonitor:
    interval: 30s

deployment:
  argocd: false

nameOverride: ""
fullnameOverride: ""
resources: {}
nodeSelector: {}
affinity: {}
tolerations: {}

