before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  binary: zadara-exporter
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - "-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64

dockers:
  - image_templates:
    - "registry.k.io/internal/zadara-exporter:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/amd64"
  - image_templates:
    - "registry.k.io/internal/zadara-exporter:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: "registry.k.io/internal/zadara-exporter:{{ .Version }}"
    image_templates:
    - "registry.k.io/internal/zadara-exporter:{{ .Version }}-amd64"
    - "registry.k.io/internal/zadara-exporter:{{ .Version }}-arm64v8"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
