listen_address: :9090
listen_path: /metrics
targets:
  - name: London
    url: https://command-center-1.zadarastorage.com
    token: "<TOKEN HERE>"
    cloud_name: cc1
  # - name: New York
  #   url: https://command-center-2.zadarastorage.com
  #   token: "<TOKEN HERE>"
  #   cloud_name: cc2
