apiVersion: v1 
kind: ConfigMap
metadata:
  name: {{ include "zadaraexporter.fullname" . }}
  labels:
    {{- include "zadaraexporter.labels" . | nindent 4 }}
data: 
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
