apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zadaraexporter.fullname" . }}
  labels:
    {{- include "zadaraexporter.labels" . | nindent 4 }}
---
# Grant the zadaraexporter permission to read the secrets containing the credentials
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zadaraexporter.fullname" . }}:secrets-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zadaraexporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ''
    resources:
    - 'secrets'
    verbs:
    - 'get'
---
# Grant the zadaraexporter permission to read the secrets containing the credentials
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zadaraexporter.fullname" . }}:secrets-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zadaraexporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "zadaraexporter.fullname" . }}:secrets-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "zadaraexporter.fullname" . }}
    namespace: {{ .Release.Namespace }}
  

