{{ if not .Values.configSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zadaraexporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zadaraexporter.labels" . | nindent 4 }}
  annotations:
    {{- include "zadaraexporter.argocdAnnotations" (dict "root" . "wave" 10) | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.config | b64enc  }}
{{ end }}
