{{ if not .Values.configSecretName}}
apiVersion: v1 
kind: Secret
metadata:
  name: {{ include "zadaraexporter.fullname" . }}
  labels:
    {{- include "zadaraexporter.labels" . | nindent 4 }}
type: Opaque
data: 
  config.yaml: {{ toYaml .Values.config | b64enc  }}
{{ end }}