apiVersion: v1
kind: Service
metadata:
  name: {{ include "zadaraexporter.fullname" . }}
  labels:
    {{- include "zadaraexporter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "zadaraexporter.argocdAnnotations" (dict "root" . "wave" 10) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zadaraexporter.selectorLabels" . | nindent 4 }}
