{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{include "zadaraexporter.generateName" (dict "root" . "suffix" "zadaraexporter")}}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "zadaraexporter.labels" . | nindent 4 }}
  annotations:
    {{- include "zadaraexporter.argocdAnnotations" (dict "root" . "wave" 10) | nindent 4 }}
spec:
  jobLabel: katapult
  endpoints:
    - honorLabels: true
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      port: http
      path: /metrics
  selector:
    matchLabels:
      {{- include "zadaraexporter.selectorLabels" . | nindent 6 }}
      k8s.katapult.io/component: zadaraexporter
{{- end}}
