---
    name: CI
    on: [push]
    
    jobs:    
      lint:
        name: Lint
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-go@v4
            with:
              go-version: "1.22"
          - name: golangci-lint
            uses: golangci/golangci-lint-action@v3
            with:
              version: v1.57
              args: --timeout=10m
            env:
              VERBOSE: "true"
    
      tidy:
        name: Tidy
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-go@v4
            with:
              go-version: "1.22"
          - name: Check if mods are tidy
            run: make check-tidy
    
      test:
        name: Test
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-go@v4
            with:
              go-version: "1.22"
          - name: Run tests
            run: make test
            env:
              TESTARGS: "-covermode=atomic -coverprofile=./coverage.out"
          - run: go tool cover -html=coverage.out -o=coverage.html
          - name: Upload coverage report to artifacts
            uses: actions/upload-artifact@v2
            with:
              name: coverage-report
              path: |
                coverage.out
                coverage.html
              if-no-files-found: error

    